### ISSUE TITLE
Make fails 

### ISSUE THREAD

**Issue by BigBobDalton** [jeremyb31/mt7601u-5.3#2]
I would like to install this on my openWRT but receive the following error when running make

make[1]: *** /lib/modules/5.10.146/build: No such file or directory.  Stop.
make: *** [Makefile:18: all] Error 2

**Comment by jeremyb31** [comment]
What is wrong with the kernel module, as this is unlikely to compile on anything newer than 5.3

**Comment by BigBobDalton** [comment]
Thanks, I gave up and ordered a different antenna 👍
